title: "AILAB"
description: "Artificial Intelligence Laboratory"
baseurl: "/ailab" # the subpath of your site, e.g. /blog
url: "https://giuseppevizzari.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: jekyll-theme-prime # Removed unsupported theme to use custom layouts
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  people:
    output: true
    permalink: /people/:path/
  projects:
    output: true
    permalink: /projects/:path/
  events:
    output: true
    permalink: /events/:path/

exclude:
  - Gemfile
  - Gemfile.lock
